export interface DeliveryRegionOption {
  value: string;
  label: string;
  slaDays: number;
}

export const DELIVERY_REGIONS: DeliveryRegionOption[] = [
  { value: 'Metro Manila', label: 'Metro Manila (1 Week)', slaDays: 7 },
  { value: 'Luzon', label: 'Provincial Luzon (10 Days)', slaDays: 10 },
  { value: 'Visayas', label: 'Visayas (14 Days)', slaDays: 14 },
  { value: 'Mindanao', label: 'Mindanao (14 Days)', slaDays: 14 },
];

export const REGION_LOCATIONS: Record<string, string[]> = {
  'Metro Manila': [
    'Caloocan',
    'Las Piñas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Manila',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Parañaque',
    'Pasay',
    'Pasig',
    'Pateros',
    'Quezon City (QC)',
    'San Juan',
    'Taguig',
    'Valenzuela',
  ],
  'Luzon': [
    'Albay (Legazpi)',
    'Aurora (Baler)',
    'Bataan (Balanga)',
    'Batanes (Basco)',
    'Batangas (Batangas City / Lipa)',
    'Benguet (Baguio City)',
    'Bulacan (Malolos / San Jose del Monte)',
    'Cagayan (Tuguegarao)',
    'Camarines Norte (Daet)',
    'Camarines Sur (Naga)',
    'Catanduanes (Virac)',
    'Cavite (Bacoor / Imus / Dasmariñas / Tagaytay)',
    'Ifugao (Lagawe)',
    'Ilocos Norte (Laoag)',
    'Ilocos Sur (Vigan)',
    'Isabela (Ilagan / Cauayan)',
    'Kalinga (Tabuk)',
    'La Union (San Fernando)',
    'Laguna (Calamba / Sta. Rosa / Biñan / San Pedro)',
    'Marinduque (Boac)',
    'Masbate (Masbate City)',
    'Mountain Province (Bontoc)',
    'Nueva Ecija (Cabanatuan / Palayan)',
    'Nueva Vizcaya (Bayombong)',
    'Occidental Mindoro (San Jose)',
    'Oriental Mindoro (Calapan)',
    'Palawan (Puerto Princesa)',
    'Pampanga (Angeles / San Fernando)',
    'Pangasinan (Dagupan / Urdaneta)',
    'Quezon Province (Lucena)',
    'Quirino (Cabarroguis)',
    'Rizal (Antipolo / Cainta / Taytay)',
    'Romblon',
    'Sorsogon (Sorsogon City)',
    'Tarlac (Tarlac City)',
    'Zambales (Olongapo / Subic)',
  ],
  'Visayas': [
    'Aklan (Kalibo / Boracay)',
    'Antique (San Jose)',
    'Biliran (Naval)',
    'Bohol (Tagbilaran)',
    'Capiz (Roxas City)',
    'Cebu (Cebu City / Mandaue / Lapu-Lapu / Talisay)',
    'Eastern Samar (Borongan)',
    'Guimaras (Jordan)',
    'Iloilo (Iloilo City)',
    'Leyte (Tacloban / Ormoc)',
    'Negros Occidental (Bacolod)',
    'Negros Oriental (Dumaguete)',
    'Northern Samar (Catarman)',
    'Samar / Western Samar (Catbalogan / Calbayog)',
    'Siquijor',
    'Southern Leyte (Maasin)',
  ],
  'Mindanao': [
    'Agusan del Norte (Butuan)',
    'Agusan del Sur (San Francisco)',
    'Basilan (Isabela City / Lamitan)',
    'Bukidnon (Malaybalay / Valencia)',
    'Camiguin (Mambajao)',
    'Cotabato City',
    'Davao City (Metro Davao)',
    'Davao de Oro (Nabunturan)',
    'Davao del Norte (Tagum / Panabo)',
    'Davao del Sur (Digos)',
    'Davao Occidental (Malita)',
    'Davao Oriental (Mati)',
    'Dinagat Islands (San Jose)',
    'General Santos City (GenSan)',
    'Iligan City (Lanao del Norte)',
    'Lanao del Sur (Marawi)',
    'Maguindanao del Norte / del Sur',
    'Misamis Occidental (Ozamiz / Oroquieta)',
    'Misamis Oriental (Cagayan de Oro)',
    'North Cotabato (Kidapawan)',
    'Sarangani (Alabel)',
    'South Cotabato (Koronadal)',
    'Sultan Kudarat (Tacurong / Isulan)',
    'Sulu (Jolo)',
    'Surigao del Norte (Surigao City / Siargao)',
    'Surigao del Sur (Tandag / Bislig)',
    'Tawi-Tawi (Bongao)',
    'Zamboanga City',
    'Zamboanga del Norte (Dipolog / Dapitan)',
    'Zamboanga del Sur (Pagadian)',
    'Zamboanga Sibugay (Ipil)',
  ],
};
