import React from 'react';
import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Gavel } from 'lucide-react';
import { Button } from '@/components/ui/button';

export const Terms = () => {
  return (
    <div className="min-h-screen bg-white font-sans selection:bg-zinc-100">
      <nav className="border-b border-zinc-100 py-4 px-6 sticky top-0 bg-white/80 backdrop-blur-md z-50">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <Link to="/" className="flex items-center gap-2">
            <span className="font-black tracking-tighter text-zinc-900">Active Pro</span>
          </Link>
          <Link to="/">
            <Button variant="ghost" size="sm" className="text-[10px] font-black uppercase tracking-widest gap-2">
              <ArrowLeft className="w-3 h-3" /> Back home
            </Button>
          </Link>
        </div>
      </nav>

      <main className="py-24 max-w-3xl mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="flex items-center gap-4 mb-8">
            <div className="bg-zinc-900 p-2 rounded-lg">
              <Gavel className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-4xl font-black tracking-tighter text-zinc-900 uppercase">Terms of Service</h1>
          </div>

          <p className="text-sm text-zinc-400 font-bold uppercase tracking-widest mb-12">Service Level Agreement (SLA) Matrix v2.4</p>

          <div className="prose prose-zinc prose-sm md:prose-base max-w-none space-y-12">
            <section>
              <h2 className="text-xl font-black tracking-tight text-zinc-900 mb-4">1. SYSTEM ACCESS</h2>
              <p className="text-zinc-600 leading-relaxed font-medium">
                Access to the Active Pro environment is restricted to authorized agents and administrators. Users are responsible for maintaining the confidentiality of their credentials. Any unauthorized access attempt will result in immediate IP termination.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-black tracking-tight text-zinc-900 mb-4">2. DATA ACCURACY</h2>
              <p className="text-zinc-600 leading-relaxed font-medium">
                Inventory levels and financial trajectory logs generated by the system are based on user input and automated triggers. Active Pro is not liable for operational losses resulting from manual data entry errors.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-black tracking-tight text-zinc-900 mb-4">3. USAGE QUOTAS</h2>
              <p className="text-zinc-600 leading-relaxed font-medium">
                Standard accounts are subject to Firebase resource quotas. Excessive API polling or abnormal database activity may trigger temporary throttling to ensure global system stability.
              </p>
            </section>

            <section className="bg-zinc-950 p-8 rounded-3xl text-white">
              <h2 className="text-xl font-black tracking-tight text-white mb-4">4. TERMINATION OF SERVICE</h2>
              <p className="text-zinc-400 leading-relaxed font-medium">
                We reserve the right to suspend any hub or account found to be violating supply chain ethical standards or attempting to reverse-engineer our reactive core engine.
              </p>
            </section>
          </div>
        </motion.div>
      </main>
    </div>
  );
};
